In [ ]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import metrics
from torch.nn.functional import binary_cross_entropy
import random
import torch
import math
from sklearn.metrics import f1_score,recall_score,precision_score,accuracy_score

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/ML_Dataset/BuyComputer.csv')
data.drop(columns=['User ID',],axis=1,inplace=True)
# data.head()

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
df = pd.DataFrame(data)
X = df.drop(["Purchased"], axis=1)
y = df["Purchased"]
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.05)
X_train

Age  EstimatedSalary
157   29            75000
198   26            80000
361   53            34000
165   18            86000
61    25            87000
..   ...              ...
190   24            84000
320   52           138000
151   41            45000
154   40            47000
16    47            25000

[380 rows x 2 columns]

In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
# X_train

In [ ]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred

array([1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1])

In [ ]:
cm = metrics.confusion_matrix(y_test, y_pred)
cm

array([[12,  2],
       [ 2,  4]])

Manually Calculation

In [ ]:
features = len(X_train)
weights = []
random.seed(5)
for i in range(3):
  weights.append(random.random())
print(features)
weights.append(random.random())

380


In [ ]:
def calculateIn(x,y,weights):
  # x=1
  # print(weights)
  ans=weights[0] + weights[1]*x + weights[2]*y
  return ans

In [ ]:
def sigmoid(input):
  return 1/(1 + np.exp(-input))

In [ ]:
def prediction(inputs,weights):
  y_pred = []
  # inputs.to_numpy()
  samples = len(inputs)
  # print(inputs)
  for x in range(samples):
    temp = calculateIn(inputs[x][0],inputs[x][1],weights)
    num =sigmoid(temp)
    # if(num>0.5):
    #   num = 1
    # else:
    #   num = 0
    y_pred.append(num)
  return y_pred

In [ ]:
y_pred_man = prediction(X_train,weights)
# y_pred_man

In [ ]:
def update_para(lossVal,weights):
  learning_rate = 0.2
  weights_new = []
  for i in range(len(weights)):
    weights_torch = torch.tensor(weights[i],requires_grad=True)
    # print(weights_torch)
    loss_torch = torch.tensor(lossVal,dtype=torch.float64,requires_grad=True)
    loss_torch.backward()
    # print(weights_torch)
    weights_new.append(weights[i] - learning_rate*(loss_torch.grad))
    # print(loss_torch.grad)
  return weights_new
  

In [ ]:
def loss(y_pred,y_act):
  temp = pd.Series(y_act)
  y_act = temp.to_numpy()
  y_pred = np.array(y_pred)
  n = y_pred.shape[0]
  lossVal = 0
  for i in range(n):
    lossVal = lossVal - (y_act[i]*math.log(y_pred[i],2) ) - ( (1-y_act[i]) * math.log(1-y_pred[i],2) )
  # print(lossVal)
  return lossVal

In [ ]:
loop = 100
weights_new = []
for i in range(loop):
  lossVal = loss(y_pred_man,y_train)
  weights_new = update_para(lossVal,weights)
  # print(weights_new)
  y_pred_man = prediction(X_train,weights_new)
  # print(y_pred_man)

In [ ]:
y_pred_test = prediction(X_test,weights_new)
y_pred_test = np.array(y_pred_test)
for i in range(len(y_pred_test)):
  if(y_pred_test[i]>0.5):
    y_pred_test[i] = 1
  else:
    y_pred_test[i] = 0
precision_score(y_test, y_pred_test), accuracy_score(y_test,  y_pred_test), recall_score(y_test,  y_pred_test), f1_score(y_test,  y_pred_test)

(0.375, 0.5, 1.0, 0.5454545454545454)

Exercise

In [ ]:
model1 = LogisticRegression(random_state=104)

model1.fit(X_train, y_train)
y_pred = model1.predict(X_test)
y_pred

cm = metrics.confusion_matrix(y_test, y_pred)
cm
# X_train,y_train
# np.array(X_test)

array([[11,  2],
       [ 1,  6]])

In [ ]:
for i in range(len(y_pred)):
  if(y_pred[i]>0.5):
    y_pred[i] = 1
  else:
    y_pred[i] = 0
precision_score(y_test, y_pred), accuracy_score(y_test,  y_pred), recall_score(y_test,  y_pred), f1_score(y_test,  y_pred)

(0.75, 0.85, 0.8571428571428571, 0.7999999999999999)

In [ ]:
predicted_val = model.predict([[12,16000]])
predicted_val[0]

1