In [ ]:
import numpy as np
import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
import tensorflow as tf
from sklearn.metrics import mean_squared_error

Data Required to train the model

In [ ]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69,96, 70], 
                   [73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96,70]], dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119], 
                    [56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119], 
                    [56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

Pytorch Implementation

In [ ]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [ ]:
tensorDataset = TensorDataset(inputs,targets)
tensorDataset[0]

(tensor([73., 67., 43.]), tensor([56., 70.]))

In [ ]:
class linearRegression(torch.nn.Module):
    def __init__(self, inputSize, outputSize):
        super(linearRegression, self).__init__()
        self.linear = torch.nn.Linear(inputSize, outputSize)
        
    def forward(self, x):
        out = self.linear(x)
        return out

In [ ]:
alpha = 0.00009
model = linearRegression(inputs.size()[1], targets.size()[1])
epochs = 100

criterion = torch.nn.MSELoss(reduction="mean")
optimizer = torch.optim.SGD(model.parameters(), lr=alpha)

for epoch in range(epochs):
    optimizer.zero_grad()
    outputs = model(inputs)
    loss = criterion(outputs, targets)
    print(loss)
    loss.backward()
    optimizer.step()

tensor(7865.5737, grad_fn=<MseLossBackward0>)
tensor(3010.0474, grad_fn=<MseLossBackward0>)
tensor(1185.8268, grad_fn=<MseLossBackward0>)
tensor(497.1205, grad_fn=<MseLossBackward0>)
tensor(234.1377, grad_fn=<MseLossBackward0>)
tensor(131.0893, grad_fn=<MseLossBackward0>)
tensor(88.4122, grad_fn=<MseLossBackward0>)
tensor(68.7785, grad_fn=<MseLossBackward0>)
tensor(58.1653, grad_fn=<MseLossBackward0>)
tensor(51.2795, grad_fn=<MseLossBackward0>)
tensor(46.1010, grad_fn=<MseLossBackward0>)
tensor(41.8391, grad_fn=<MseLossBackward0>)
tensor(38.1673, grad_fn=<MseLossBackward0>)
tensor(34.9361, grad_fn=<MseLossBackward0>)
tensor(32.0655, grad_fn=<MseLossBackward0>)
tensor(29.5039, grad_fn=<MseLossBackward0>)
tensor(27.2130, grad_fn=<MseLossBackward0>)
tensor(25.1614, grad_fn=<MseLossBackward0>)
tensor(23.3222, grad_fn=<MseLossBackward0>)
tensor(21.6720, grad_fn=<MseLossBackward0>)
tensor(20.1899, grad_fn=<MseLossBackward0>)
tensor(18.8576, grad_fn=<MseLossBackward0>)
tensor(17.6587, grad_fn

In [ ]:
predicted = model(inputs)
predicted , targets

(tensor([[ 57.1837,  70.4761],
         [ 81.6164,  99.2966],
         [120.0051, 135.8138],
         [ 21.4759,  37.9026],
         [100.5925, 116.2169],
         [ 57.1837,  70.4761],
         [ 81.6164,  99.2966],
         [120.0051, 135.8138],
         [ 21.4759,  37.9026],
         [100.5925, 116.2169],
         [ 57.1837,  70.4761],
         [ 81.6164,  99.2966],
         [120.0051, 135.8138],
         [ 21.4759,  37.9026],
         [100.5925, 116.2169]], grad_fn=<AddmmBackward0>),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.],
         [ 56.,  70.],
         [ 81., 101.],
         [119., 133.],
         [ 22.,  37.],
         [103., 119.]]))

Sklearn Implementation

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(inputs, targets, test_size=0.2)

model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)

err = mean_squared_error(y_test, predictions)
predictions, y_test,model.coef_,err

(array([[ 82.46687 , 100.897194],
        [101.80545 , 119.08373 ],
        [ 21.059692,  37.065907]], dtype=float32), tensor([[ 81., 101.],
         [103., 119.],
         [ 22.,  37.]]), array([[-0.3779492 ,  0.8492347 ,  0.7049694 ],
        [-0.28583288,  0.7939031 ,  0.9244994 ]], dtype=float32), 0.7474613)

In [ ]:
mean_squared_error(predictions, y_test)

0.7067486

Tensorflow Implementation

In [ ]:
learning_rate = 0.0009
training_epochs = 100

Weights1 = np.random.normal(size=(X_train[0].shape))
Weights2 = np.random.normal(size=(X_train[0].shape))
Bais1 = [1]
Bais2 = [2]


In [ ]:
predictions1 = tf.math.reduce_sum(tf.add(tf.multiply(X_train, Weights1), Bais1), axis=1)
predictions2 = tf.math.reduce_sum(tf.add(tf.multiply(X_train, Weights2), Bais2), axis=1)
predictions1

prediction = tf. convert_to_tensor(np.transpose(tf.concat([[predictions1,predictions2]], axis=1)))
prediction

<tf.Tensor: shape=(12, 2), dtype=float32, numpy=
array([[ 5.7780075e-01, -1.7177267e+02],
       [ 5.8937750e+00, -5.6257240e+01],
       [ 5.7780075e-01, -1.7177267e+02],
       [-8.3081245e-02, -1.2797947e+02],
       [ 5.8937750e+00, -5.6257240e+01],
       [-3.2574196e+00, -1.4455942e+02],
       [ 2.0412159e+00, -9.0626831e+01],
       [-3.2574196e+00, -1.4455942e+02],
       [ 2.0412159e+00, -9.0626831e+01],
       [-8.3081245e-02, -1.2797947e+02],
       [-3.2574196e+00, -1.4455942e+02],
       [ 5.7780075e-01, -1.7177267e+02]], dtype=float32)>

In [ ]:
loss =  tf.math.reduce_sum(tf.pow(prediction - y_train, 2) / (2 * X_train.shape[0]),axis = 0)
loss 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3976.426, 27537.867], dtype=float32)>