### Probablistic Models in Machine Learning

1. Naive Bayes Classifier

In [ ]:
# Import the necessary libraries

import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB, MultinomialNB, CategoricalNB

In [ ]:
# Creating the dataset

weather = np.array(['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy'])

temp = np.array(['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
'Cool','Mild','Mild','Mild','Hot','Mild'])

play = np.array(['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
'Yes','Yes','Yes','Yes','No'])

In [ ]:
# Prime the data by filtering it

le = LabelEncoder()
weather_encoded = le.fit_transform(weather)
temp_encoded = le.fit_transform(temp)
label = le.fit_transform(play)
weather_encoded, temp_encoded, label

In [ ]:
# Combine the features to feed them into the model

features = tuple(zip(weather_encoded, temp_encoded))
features

In [ ]:
# Create a classifier

# model = MultinomialNB()
# model = GaussianNB()
model = CategoricalNB()
model.fit(features, label)

# weather_input = int(input())
# temp_input = int(input())

predictions = []
for i in range(3):
    for j in range(3):
        predictions[:0] = model.predict([[i, j]])

predictions

2. Gaussian Classifier Iris Dataset

In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()

In [ ]:
iris.feature_names

In [ ]:
iris.target_names 

In [ ]:
newdata = iris.data[50:]
newtargets = iris.target[50:]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(newdata, newtargets, test_size=0.25, random_state=5)

gnb = GaussianNB()
gnb.fit(X_train, y_train)
predictions = gnb.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score

In [ ]:
score = accuracy_score(y_test, predictions)
score

In [ ]:
confusion_matrix(y_test, predictions)

In [ ]:
score = precision_score(y_test, predictions)
score

In [ ]:
score = recall_score(y_test, predictions)
score

3. Gaussian Classifier Iris Dataset (3 Classes)

Task #1

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [ ]:
data = pd.read_csv("drive/MyDrive/Dataset2.csv")
data

Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N

In [ ]:
le = LabelEncoder()

In [ ]:
for i in data:
    data[i] = le.fit_transform(data[i])

In [ ]:
features = data.iloc[:, :-1]
labels = data.iloc[:, -1:]

In [ ]:
features

In [ ]:
labels

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.1, random_state=1)

In [ ]:
gnb = GaussianNB()
gnb.fit(X_train, y_train.values.ravel())
predictions = gnb.predict(X_test)
predictions

array([1, 1])

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

In [ ]:
score = accuracy_score(y_test, predictions)
score

0.5

In [ ]:
score = precision_score(y_test, predictions)
score

0.5

In [ ]:
score = recall_score(y_test, predictions)
score

1.0

In [ ]:
cfm = confusion_matrix(y_test, predictions)
cfm

array([[0, 1],
       [0, 1]])

Task #2

In [ ]:
digits = datasets.load_digits()

In [ ]:
features = np.array(digits.feature_names)
features

array(['pixel_0_0', 'pixel_0_1', 'pixel_0_2', 'pixel_0_3', 'pixel_0_4',
       'pixel_0_5', 'pixel_0_6', 'pixel_0_7', 'pixel_1_0', 'pixel_1_1',
       'pixel_1_2', 'pixel_1_3', 'pixel_1_4', 'pixel_1_5', 'pixel_1_6',
       'pixel_1_7', 'pixel_2_0', 'pixel_2_1', 'pixel_2_2', 'pixel_2_3',
       'pixel_2_4', 'pixel_2_5', 'pixel_2_6', 'pixel_2_7', 'pixel_3_0',
       'pixel_3_1', 'pixel_3_2', 'pixel_3_3', 'pixel_3_4', 'pixel_3_5',
       'pixel_3_6', 'pixel_3_7', 'pixel_4_0', 'pixel_4_1', 'pixel_4_2',
       'pixel_4_3', 'pixel_4_4', 'pixel_4_5', 'pixel_4_6', 'pixel_4_7',
       'pixel_5_0', 'pixel_5_1', 'pixel_5_2', 'pixel_5_3', 'pixel_5_4',
       'pixel_5_5', 'pixel_5_6', 'pixel_5_7', 'pixel_6_0', 'pixel_6_1',
       'pixel_6_2', 'pixel_6_3', 'pixel_6_4', 'pixel_6_5', 'pixel_6_6',
       'pixel_6_7', 'pixel_7_0', 'pixel_7_1', 'pixel_7_2', 'pixel_7_3',
       'pixel_7_4', 'pixel_7_5', 'pixel_7_6', 'pixel_7_7'], dtype='<U9')

In [ ]:
labels = np.array(digits.target_names)
labels

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [ ]:
# therefore, 1797 are the number of data entries and 64 are the features
digits.target.shape, digits.data.shape

((1797,), (1797, 64))

In [ ]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder()
# features_encoded = ohe.fit_transform(features.reshape(-1,1)).toarray()
# print(features_encoded.shape)

In [ ]:
labels_encoded = ohe.fit_transform(digits.target.reshape(-1,1)).toarray()
labels_encoded

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.35)

In [ ]:
gnb.fit(X_train, y_train)
predictions = gnb.predict(X_test)
predictions

array([6, 0, 1, 8, 4, 7, 6, 1, 4, 9, 1, 0, 7, 8, 6, 8, 8, 8, 4, 7, 0, 7,
       2, 0, 0, 3, 2, 6, 6, 4, 3, 0, 9, 8, 8, 5, 4, 0, 1, 8, 8, 0, 2, 3,
       9, 2, 4, 9, 6, 8, 7, 1, 2, 6, 0, 1, 3, 7, 7, 9, 4, 7, 5, 7, 0, 1,
       7, 9, 0, 8, 0, 1, 9, 0, 9, 4, 6, 0, 1, 3, 6, 8, 8, 7, 7, 8, 6, 5,
       7, 7, 5, 7, 5, 8, 6, 6, 7, 8, 3, 7, 5, 2, 1, 5, 6, 1, 6, 8, 8, 8,
       0, 2, 6, 0, 9, 9, 6, 0, 4, 1, 6, 0, 0, 8, 7, 6, 8, 4, 2, 4, 8, 7,
       7, 3, 7, 6, 6, 9, 4, 0, 8, 5, 4, 2, 5, 7, 6, 3, 8, 3, 0, 4, 0, 5,
       6, 6, 7, 4, 4, 2, 1, 1, 1, 0, 0, 9, 9, 7, 7, 4, 7, 4, 8, 0, 0, 4,
       1, 7, 8, 8, 5, 1, 3, 5, 2, 0, 4, 6, 2, 5, 3, 2, 1, 8, 7, 4, 6, 8,
       6, 2, 5, 4, 0, 1, 5, 4, 8, 2, 3, 3, 8, 5, 1, 7, 9, 6, 5, 0, 0, 8,
       8, 5, 7, 3, 1, 7, 8, 9, 8, 3, 3, 5, 5, 4, 7, 7, 5, 5, 0, 0, 1, 6,
       6, 9, 5, 1, 5, 7, 0, 0, 6, 9, 7, 3, 6, 7, 1, 6, 5, 6, 1, 1, 4, 7,
       4, 2, 1, 7, 1, 8, 3, 2, 3, 7, 8, 7, 9, 5, 8, 8, 4, 9, 3, 9, 8, 4,
       8, 3, 1, 7, 7, 5, 5, 5, 2, 4, 6, 0, 9, 0, 6,

In [ ]:
precision_score(y_test, predictions, average="micro")

0.8664546899841018

In [ ]:
accuracy_score(y_test, predictions)

0.8664546899841018

In [ ]:
recall_score(y_test, predictions, average="micro")

0.8664546899841018